### ISSUE TITLE
Lwjgl 3 Not working

### ISSUE THREAD

**Issue by Termin8or** [cjstehno/gradle-natives#15]
I implemented this with the hope of handling Lwjgl3 natives however when I run the command, the natives folders remain empty. I assume it's because the natives have changed. Is this project still active?

**Comment by cjstehno** [comment]
Yes and no... it seems to have some users so I try to keep it up to date, but I don't use it myself.. Yes, I believe they moved the native libs in Lwjgl 3. When I last checked it had not been released yet so I held off updating. I should be able to address this by mid next week. If you are so inclined, I am open to pull requests.

**Comment by cjstehno** [comment]
They moved the native libraries from an OS-differentiated structure to a flat structure so now all the native libs are in one `native` directory rather than OS-specific sub-directories (e.g. `native/windows`). Currently this plugin is based on the OS-specific directory structure, which seemed like a common format if not a standard at the time - I guess that was a poor assumption. Work will need to be done to refactor the way natives are resolved from the jars in a more flexible manner.

I have not used this plugin in quite a while. I will address this issue; however, I cannot say when I will get to work on it since I have other interests more directly related to what I am working on right now. Sometimes things like this bug me until I fix them, but you never know.

**Comment by Termin8or** [comment]
I would love to help with this but have no clue how gradle plugins work, for now im setting them up manually, and will wait for further development.

**Comment by bwRavencl** [comment]
**Qt-Jambi** seems to be affected by this issue as well. The windows .dlls simply reside in a directory called 'lib':
`./lib/*.dll`

**Comment by cjstehno** [comment]
I have started working on fixing the issues with this plugin... expect a new release in a week or two.

**Comment by cjstehno** [comment]
This has been addressed in the development branch - will be released within a day or two.
